version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0.9'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  j17:
    docker:
      - image: 'cimg/openjdk:21.0.9'

orbs:
  maven: circleci/maven@2.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j17
      - build:
          context: SonarCloud